# Generated by Django 4.0.4 on 2022-04-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=30)),
                ('reg_num', models.CharField(max_length=12)),
                ('discount_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_password', models.CharField(max_length=32)),
                ('user_phone', models.CharField(blank=True, max_length=10)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_type', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('driver_lic_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Individual_customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CarRental.user')),
                ('policy_num', models.CharField(max_length=15)),
                ('insurance_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Insurance', to='CarRental.insurance_company')),
            ],
            bases=('CarRental.user',),
        ),
        migrations.CreateModel(
            name='Corporate_customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CarRental.user')),
                ('emp_id', models.IntegerField()),
                ('corp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate', to='CarRental.corporation')),
            ],
            bases=('CarRental.user',),
        ),
    ]
