# Generated by Django 4.0.4 on 2022-05-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('daily_rate', models.FloatField()),
                ('over_mile_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_year', models.IntegerField()),
                ('plate_num', models.CharField(max_length=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_vehicles', to='CarRental.vehicle_class')),
                ('office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_vehicles', to='CarRental.office')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('start_odometer', models.FloatField(blank=True)),
                ('end_odometer', models.FloatField(blank=True)),
                ('daily_limit', models.IntegerField(blank=True)),
                ('corporate_cust_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Corporate_cust_rervations', to='CarRental.corporate_customer')),
                ('coupun_num', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_rervations', to='CarRental.coupon')),
                ('individual_cust_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Individual_cust_rervations', to='CarRental.individual_customer')),
                ('office_dropoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_office_rervations', to='CarRental.office')),
                ('office_pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pickup_office_rervations', to='CarRental.office')),
                ('rental_invoice_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_rervations', to='CarRental.invoice')),
                ('vehicle_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rervations', to='CarRental.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('payment_date', models.DateField()),
                ('card_number', models.CharField(max_length=16)),
                ('payment_amount', models.FloatField()),
                ('invoice_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='CarRental.invoice')),
            ],
        ),
    ]
