# Generated by Django 4.0.4 on 2022-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0002_coupon_invoice_office_vehicle_class_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_num',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
