# Generated by Django 4.0.4 on 2022-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0003_coupon_coupon_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_service',
            name='end_odometer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
