# Generated by Django 4.0.4 on 2022-05-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0004_alter_rental_service_end_odometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_service',
            name='corporate_cust_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Corporate_cust_rervations', to='CarRental.corporate_customer'),
        ),
        migrations.AlterField(
            model_name='rental_service',
            name='coupun_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_rervations', to='CarRental.coupon'),
        ),
        migrations.AlterField(
            model_name='rental_service',
            name='individual_cust_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Individual_cust_rervations', to='CarRental.individual_customer'),
        ),
        migrations.AlterField(
            model_name='rental_service',
            name='rental_invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_rervations', to='CarRental.invoice'),
        ),
        migrations.AlterField(
            model_name='rental_service',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rervations', to='CarRental.vehicle'),
        ),
    ]
