# Generated by Django 4.0.4 on 2022-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0007_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_service',
            name='start_odometer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
