# Generated by Django 4.0.4 on 2022-05-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0008_alter_rental_service_start_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_date',
            field=models.CharField(default=1123, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='name_on_card',
            field=models.CharField(default='john', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental_service',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rervations', to='CarRental.vehicle_class'),
        ),
    ]
