# Generated by Django 4.0.4 on 2022-05-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0009_payment_cvv_payment_exp_date_payment_name_on_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental_service',
            name='vehicle_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_class_rervations', to='CarRental.vehicle_class'),
        ),
        migrations.AlterField(
            model_name='rental_service',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rervations', to='CarRental.vehicle'),
        ),
    ]
